a=input("enter your text:")
a=a.swapcase()
print("upper to lower and vice versa:",a)
a=a.capitalize()
print("first letter captial:",a)
a=a.title()
print("captials when text separated by space:",a)
a=a.upper()
print("upper case :",a)
a=a.lower()
print("lower case:",a)
